trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - PrizeDraw.ZoomWebhook.Api

variables:
  azureServicePrincipal: k8s-cluster

stages:
  # Build
  - template: Templates/Build.yaml
    parameters:
      dockerFile: $(System.DefaultWorkingDirectory)/PrizeDraw.ZoomWebhook.Api/Dockerfile
      dockerRepository: dracan/prizedraw-zoomwebhook
      buildContext: $(System.DefaultWorkingDirectory)/PrizeDraw.ZoomWebhook.Api/
      helmChartPath: $(System.DefaultWorkingDirectory)/PrizeDraw.ZoomWebhook.Api/DevOps/WebChart/

  # Deploy
  - template: Templates/Deploy.yaml
    parameters:
      environment: uat
      tag: $(Build.BuildId)
      name: web
      appInsightsInstrumentationKey: $(appInsightsInstrumentationKey)
      keyVaultUri: $(keyVaultUri)
      managedIdentityResourceId: $(managedIdentityResourceId)
      managedIdentityClientId: $(managedIdentityClientId)