apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.config.appInsightsInstrumentationKey | quote }}
  ASPNETCORE_ENVIRONMENT: 'Production'
  KeyVaultUri: {{ .Values.config.keyVaultUri | quote }}
